export const data1 = {
  id: 4,
  title: "C.S.E 4th Year",
  isActive: true,
  totalStudents: 1,
  totalClasses: 8,
  created: "2021-01-25",
  verifiedFaculties: 2,
  totalFaculties: 3,
  weekdayData: {
    Sunday: [],
    Monday: [
      {
        created: "8 days ago",
        duration: "60 Mins",
        endTime: "10:00AM",
        facultyName: "Amit Maurya",
        id: 13,
        startTime: "09:00AM",
        title: "Distributed System",
      },
      {
        created: "8 days ago",
        duration: "59 Mins",
        endTime: "11:00AM",
        facultyName: "Ramjeet Yadav",
        id: 14,
        startTime: "10:01AM",
        title: "Human Values",
      },
      {
        created: "8 days ago",
        duration: "59 Mins",
        endTime: "12:00PM",
        facultyName: "Amit Maurya",
        id: 15,
        startTime: "11:01AM",
        title: "Human Values",
      },
      {
        created: "8 days ago",
        duration: "75 Mins",
        endTime: "02:15PM",
        facultyName: "Amit Maurya",
        id: 16,
        startTime: "01:00PM",
        title: "Electrical System",
      },
    ],
    Tuesday: [
      {
        created: "8 days ago",
        duration: "60 Mins",
        endTime: "10:00AM",
        facultyName: "Amit Maurya",
        id: 17,
        startTime: "09:00AM",
        title: "Distributed System",
      },

      {
        created: "8 days ago",
        duration: "75 Mins",
        endTime: "02:15PM",
        facultyName: "Amit Maurya",
        id: 20,
        startTime: "01:00PM",
        title: "Electrical System",
      },
    ],
    Wednesday: [
      {
        created: "8 days ago",
        duration: "60 Mins",
        endTime: "10:00AM",
        facultyName: "Amit Maurya",
        id: 21,
        startTime: "09:00AM",
        title: "Distributed System",
      },
      {
        created: "8 days ago",
        duration: "59 Mins",
        endTime: "11:00AM",
        facultyName: "Ramjeet Yadav",
        id: 22,
        startTime: "10:01AM",
        title: "Human Values",
      },
      {
        created: "8 days ago",
        duration: "59 Mins",
        endTime: "12:00PM",
        facultyName: "Amit Maurya",
        id: 23,
        startTime: "11:01AM",
        title: "Human Values",
      },
      {
        created: "8 days ago",
        duration: "75 Mins",
        endTime: "02:15PM",
        facultyName: "Amit Maurya",
        id: 24,
        startTime: "01:00PM",
        title: "Electrical System",
      },
    ],
    Thursday: [
      {
        created: "8 days ago",
        duration: "60 Mins",
        endTime: "10:00AM",
        facultyName: "Amit Maurya",
        id: 25,
        startTime: "09:00AM",
        title: "Distributed System",
      },
      {
        created: "8 days ago",
        duration: "59 Mins",
        endTime: "11:00AM",
        facultyName: "Ramjeet Yadav",
        id: 26,
        startTime: "10:01AM",
        title: "Human Values",
      },
      {
        created: "8 days ago",
        duration: "59 Mins",
        endTime: "12:00PM",
        facultyName: "Amit Maurya",
        id: 27,
        startTime: "11:01AM",
        title: "Human Values",
      },
      {
        created: "8 days ago",
        duration: "75 Mins",
        endTime: "02:15PM",
        facultyName: "Amit Maurya",
        id: 28,
        startTime: "01:00PM",
        title: "Electrical System",
      },
    ],
    Friday: [
      {
        created: "8 days ago",
        duration: "60 Mins",
        endTime: "10:00AM",
        facultyName: "Amit Maurya",
        id: 29,
        startTime: "09:00AM",
        title: "Distributed System",
      },
      {
        created: "8 days ago",
        duration: "59 Mins",
        endTime: "11:00AM",
        facultyName: "Ramjeet Yadav",
        id: 30,
        startTime: "10:01AM",
        title: "Human Values",
      },
      {
        created: "8 days ago",
        duration: "59 Mins",
        endTime: "12:00PM",
        facultyName: "Amit Maurya",
        id: 31,
        startTime: "11:01AM",
        title: "Human Values",
      },
      {
        created: "8 days ago",
        duration: "75 Mins",
        endTime: "02:15PM",
        facultyName: "Amit Maurya",
        id: 32,
        startTime: "01:00PM",
        title: "Electrical System",
      },
    ],
    Saturday: [
      {
        created: "8 days ago",
        duration: "60 Mins",
        endTime: "10:00AM",
        facultyName: "Amit Maurya",
        id: 33,
        startTime: "09:00AM",
        title: "Distributed System",
      },
      {
        created: "8 days ago",
        duration: "59 Mins",
        endTime: "11:00AM",
        facultyName: "Ramjeet Yadav",
        id: 34,
        startTime: "10:01AM",
        title: "Human Values",
      },
      {
        created: "8 days ago",
        duration: "59 Mins",
        endTime: "12:00PM",
        facultyName: "Amit Maurya",
        id: 35,
        startTime: "11:01AM",
        title: "Human Values",
      },
      {
        created: "8 days ago",
        duration: "75 Mins",
        endTime: "02:15PM",
        facultyName: "Amit Maurya",
        id: 36,
        startTime: "01:00PM",
        title: "Electrical System",
      },
    ],
  },
};

export const data2 = {
  id: 1,
  title: "CSE 3RD YEAR",
  isActive: true,
  totalStudents: 2,
  totalClasses: 179,
  created: "2021-05-10",
  verifiedFaculties: 2,
  totalFaculties: 5,
  weekdayData: {
    Monday: [
      {
        id: 301,
        title: "New Class",
        startTime: "12:36 AM",
        endTime: "12:39 AM",
        duration: "3 Mins",
        created: "28 days ago",
        facultyName: "Saumya Singh",
      },
      {
        id: 2,
        title: "class_1",
        startTime: "12:40 AM",
        endTime: "01:25 AM",
        duration: "45 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 3,
        title: "class_2",
        startTime: "01:40 AM",
        endTime: "02:30 AM",
        duration: "50 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 4,
        title: "class_3",
        startTime: "02:35 AM",
        endTime: "03:30 AM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 5,
        title: "class_4",
        startTime: "03:45 AM",
        endTime: "04:25 AM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 6,
        title: "class_5",
        startTime: "04:37 AM",
        endTime: "05:32 AM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 7,
        title: "class_6",
        startTime: "05:47 AM",
        endTime: "06:17 AM",
        duration: "30 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 8,
        title: "class_7",
        startTime: "06:27 AM",
        endTime: "07:27 AM",
        duration: "60 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 9,
        title: "class_8",
        startTime: "07:35 AM",
        endTime: "08:20 AM",
        duration: "45 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 10,
        title: "class_9",
        startTime: "08:27 AM",
        endTime: "08:57 AM",
        duration: "30 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 11,
        title: "class_10",
        startTime: "09:07 AM",
        endTime: "10:07 AM",
        duration: "60 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 12,
        title: "class_11",
        startTime: "10:10 AM",
        endTime: "11:00 AM",
        duration: "50 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 13,
        title: "class_12",
        startTime: "11:05 AM",
        endTime: "11:55 AM",
        duration: "50 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 14,
        title: "class_13",
        startTime: "12:10 PM",
        endTime: "01:05 PM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 15,
        title: "class_14",
        startTime: "01:20 PM",
        endTime: "01:50 PM",
        duration: "30 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 16,
        title: "class_15",
        startTime: "01:52 PM",
        endTime: "02:47 PM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 17,
        title: "class_16",
        startTime: "02:50 PM",
        endTime: "03:20 PM",
        duration: "30 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 18,
        title: "class_17",
        startTime: "03:25 PM",
        endTime: "04:15 PM",
        duration: "50 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 19,
        title: "class_18",
        startTime: "04:25 PM",
        endTime: "05:20 PM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 20,
        title: "class_19",
        startTime: "05:22 PM",
        endTime: "05:52 PM",
        duration: "30 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 21,
        title: "class_20",
        startTime: "06:02 PM",
        endTime: "06:42 PM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 22,
        title: "class_21",
        startTime: "06:45 PM",
        endTime: "07:15 PM",
        duration: "30 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 23,
        title: "class_22",
        startTime: "07:27 PM",
        endTime: "08:17 PM",
        duration: "50 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 24,
        title: "class_23",
        startTime: "08:20 PM",
        endTime: "09:10 PM",
        duration: "50 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 25,
        title: "class_24",
        startTime: "09:17 PM",
        endTime: "10:12 PM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 26,
        title: "class_25",
        startTime: "10:15 PM",
        endTime: "11:10 PM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
    ],
    Tuesday: [
      {
        id: 28,
        title: "class_27",
        startTime: "12:57 AM",
        endTime: "01:42 AM",
        duration: "45 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 29,
        title: "class_28",
        startTime: "01:47 AM",
        endTime: "02:22 AM",
        duration: "35 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 30,
        title: "class_29",
        startTime: "02:25 AM",
        endTime: "03:25 AM",
        duration: "60 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 31,
        title: "class_30",
        startTime: "03:30 AM",
        endTime: "04:30 AM",
        duration: "60 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 32,
        title: "class_31",
        startTime: "04:45 AM",
        endTime: "05:25 AM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 33,
        title: "class_32",
        startTime: "05:30 AM",
        endTime: "06:25 AM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 34,
        title: "class_33",
        startTime: "06:37 AM",
        endTime: "07:37 AM",
        duration: "60 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 35,
        title: "class_34",
        startTime: "07:52 AM",
        endTime: "08:32 AM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 36,
        title: "class_35",
        startTime: "08:47 AM",
        endTime: "09:32 AM",
        duration: "45 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 37,
        title: "class_36",
        startTime: "09:42 AM",
        endTime: "10:12 AM",
        duration: "30 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 38,
        title: "class_37",
        startTime: "10:25 AM",
        endTime: "11:25 AM",
        duration: "60 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 39,
        title: "class_38",
        startTime: "11:35 AM",
        endTime: "12:05 PM",
        duration: "30 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 40,
        title: "class_39",
        startTime: "12:15 PM",
        endTime: "01:05 PM",
        duration: "50 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 41,
        title: "class_40",
        startTime: "01:20 PM",
        endTime: "02:15 PM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 42,
        title: "class_41",
        startTime: "02:17 PM",
        endTime: "03:02 PM",
        duration: "45 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 43,
        title: "class_42",
        startTime: "03:15 PM",
        endTime: "03:55 PM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 44,
        title: "class_43",
        startTime: "03:57 PM",
        endTime: "04:52 PM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 45,
        title: "class_44",
        startTime: "04:57 PM",
        endTime: "05:57 PM",
        duration: "60 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 46,
        title: "class_45",
        startTime: "06:10 PM",
        endTime: "07:05 PM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 47,
        title: "class_46",
        startTime: "07:17 PM",
        endTime: "08:02 PM",
        duration: "45 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 48,
        title: "class_47",
        startTime: "08:05 PM",
        endTime: "09:05 PM",
        duration: "60 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 49,
        title: "class_48",
        startTime: "09:15 PM",
        endTime: "10:15 PM",
        duration: "60 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 50,
        title: "class_49",
        startTime: "10:27 PM",
        endTime: "11:22 PM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
    ],
    Wednesday: [
      {
        id: 54,
        title: "class_53",
        startTime: "03:02 AM",
        endTime: "03:47 AM",
        duration: "45 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 55,
        title: "class_54",
        startTime: "03:52 AM",
        endTime: "04:37 AM",
        duration: "45 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 56,
        title: "class_55",
        startTime: "04:50 AM",
        endTime: "05:30 AM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 57,
        title: "class_56",
        startTime: "05:35 AM",
        endTime: "06:10 AM",
        duration: "35 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 58,
        title: "class_57",
        startTime: "06:22 AM",
        endTime: "07:17 AM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 59,
        title: "class_58",
        startTime: "07:22 AM",
        endTime: "08:07 AM",
        duration: "45 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 60,
        title: "class_59",
        startTime: "08:22 AM",
        endTime: "09:07 AM",
        duration: "45 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 61,
        title: "class_60",
        startTime: "09:12 AM",
        endTime: "09:42 AM",
        duration: "30 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 62,
        title: "class_61",
        startTime: "09:52 AM",
        endTime: "10:47 AM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 63,
        title: "class_62",
        startTime: "10:50 AM",
        endTime: "11:25 AM",
        duration: "35 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 64,
        title: "class_63",
        startTime: "11:40 AM",
        endTime: "12:20 PM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 65,
        title: "class_64",
        startTime: "12:30 PM",
        endTime: "01:05 PM",
        duration: "35 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 66,
        title: "class_65",
        startTime: "01:15 PM",
        endTime: "01:50 PM",
        duration: "35 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 67,
        title: "class_66",
        startTime: "01:57 PM",
        endTime: "02:37 PM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 68,
        title: "class_67",
        startTime: "02:52 PM",
        endTime: "03:32 PM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 69,
        title: "class_68",
        startTime: "03:37 PM",
        endTime: "04:37 PM",
        duration: "60 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 71,
        title: "class_70",
        startTime: "05:30 PM",
        endTime: "06:00 PM",
        duration: "30 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 72,
        title: "class_71",
        startTime: "06:05 PM",
        endTime: "06:55 PM",
        duration: "50 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 73,
        title: "class_72",
        startTime: "07:00 PM",
        endTime: "07:30 PM",
        duration: "30 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 74,
        title: "class_73",
        startTime: "07:35 PM",
        endTime: "08:35 PM",
        duration: "60 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 75,
        title: "class_74",
        startTime: "08:37 PM",
        endTime: "09:37 PM",
        duration: "60 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 76,
        title: "class_75",
        startTime: "09:52 PM",
        endTime: "10:37 PM",
        duration: "45 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 77,
        title: "class_76",
        startTime: "10:50 PM",
        endTime: "11:25 PM",
        duration: "35 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 303,
        title: "Thats what she saidddd!!!!!!!",
        startTime: "11:30 PM",
        endTime: "11:50 PM",
        duration: "20 Mins",
        created: "19 days ago",
        facultyName: "Omprakash Tiwari",
      },
    ],
    Thursday: [
      {
        id: 78,
        title: "class_77",
        startTime: "12:00 AM",
        endTime: "12:30 AM",
        duration: "30 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 79,
        title: "class_78",
        startTime: "12:40 AM",
        endTime: "01:20 AM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 80,
        title: "class_79",
        startTime: "01:30 AM",
        endTime: "02:30 AM",
        duration: "60 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 81,
        title: "class_80",
        startTime: "02:42 AM",
        endTime: "03:17 AM",
        duration: "35 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 82,
        title: "class_81",
        startTime: "03:27 AM",
        endTime: "04:17 AM",
        duration: "50 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 83,
        title: "class_82",
        startTime: "04:25 AM",
        endTime: "04:55 AM",
        duration: "30 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 84,
        title: "class_83",
        startTime: "05:10 AM",
        endTime: "06:00 AM",
        duration: "50 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 85,
        title: "class_84",
        startTime: "06:12 AM",
        endTime: "07:07 AM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 86,
        title: "class_85",
        startTime: "07:10 AM",
        endTime: "08:10 AM",
        duration: "60 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 87,
        title: "class_86",
        startTime: "08:17 AM",
        endTime: "09:12 AM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 88,
        title: "class_87",
        startTime: "09:20 AM",
        endTime: "09:50 AM",
        duration: "30 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 89,
        title: "class_88",
        startTime: "10:02 AM",
        endTime: "10:32 AM",
        duration: "30 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 90,
        title: "class_89",
        startTime: "10:47 AM",
        endTime: "11:22 AM",
        duration: "35 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 91,
        title: "class_90",
        startTime: "11:27 AM",
        endTime: "12:27 PM",
        duration: "60 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 92,
        title: "class_91",
        startTime: "12:37 PM",
        endTime: "01:27 PM",
        duration: "50 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 93,
        title: "class_92",
        startTime: "01:32 PM",
        endTime: "02:12 PM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 94,
        title: "class_93",
        startTime: "02:22 PM",
        endTime: "03:22 PM",
        duration: "60 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 95,
        title: "class_94",
        startTime: "03:27 PM",
        endTime: "04:07 PM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 96,
        title: "class_95",
        startTime: "04:15 PM",
        endTime: "05:00 PM",
        duration: "45 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 97,
        title: "class_96",
        startTime: "05:07 PM",
        endTime: "05:47 PM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 98,
        title: "class_97",
        startTime: "05:57 PM",
        endTime: "06:42 PM",
        duration: "45 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 99,
        title: "class_98",
        startTime: "06:47 PM",
        endTime: "07:27 PM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 100,
        title: "class_99",
        startTime: "07:32 PM",
        endTime: "08:17 PM",
        duration: "45 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 101,
        title: "class_100",
        startTime: "08:25 PM",
        endTime: "09:05 PM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 102,
        title: "class_101",
        startTime: "09:10 PM",
        endTime: "09:45 PM",
        duration: "35 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 103,
        title: "class_102",
        startTime: "09:55 PM",
        endTime: "10:40 PM",
        duration: "45 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 104,
        title: "class_103",
        startTime: "10:52 PM",
        endTime: "11:37 PM",
        duration: "45 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
    ],
    Friday: [
      {
        id: 105,
        title: "class_104",
        startTime: "12:00 AM",
        endTime: "12:55 AM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 106,
        title: "class_105",
        startTime: "01:05 AM",
        endTime: "01:45 AM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 107,
        title: "class_106",
        startTime: "01:47 AM",
        endTime: "02:22 AM",
        duration: "35 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 108,
        title: "class_107",
        startTime: "02:25 AM",
        endTime: "03:00 AM",
        duration: "35 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 109,
        title: "class_108",
        startTime: "03:02 AM",
        endTime: "03:37 AM",
        duration: "35 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 110,
        title: "class_109",
        startTime: "03:47 AM",
        endTime: "04:27 AM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 111,
        title: "class_110",
        startTime: "04:30 AM",
        endTime: "05:10 AM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 112,
        title: "class_111",
        startTime: "05:25 AM",
        endTime: "06:25 AM",
        duration: "60 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 113,
        title: "class_112",
        startTime: "06:40 AM",
        endTime: "07:20 AM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 114,
        title: "class_113",
        startTime: "07:27 AM",
        endTime: "08:12 AM",
        duration: "45 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 115,
        title: "class_114",
        startTime: "08:25 AM",
        endTime: "09:20 AM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 116,
        title: "class_115",
        startTime: "09:35 AM",
        endTime: "10:05 AM",
        duration: "30 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 117,
        title: "class_116",
        startTime: "10:10 AM",
        endTime: "10:55 AM",
        duration: "45 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 118,
        title: "class_117",
        startTime: "11:10 AM",
        endTime: "12:10 PM",
        duration: "60 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 119,
        title: "class_118",
        startTime: "12:20 PM",
        endTime: "12:50 PM",
        duration: "30 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 120,
        title: "class_119",
        startTime: "12:57 PM",
        endTime: "01:47 PM",
        duration: "50 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 121,
        title: "class_120",
        startTime: "01:50 PM",
        endTime: "02:25 PM",
        duration: "35 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 122,
        title: "class_121",
        startTime: "02:35 PM",
        endTime: "03:15 PM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 123,
        title: "class_122",
        startTime: "03:17 PM",
        endTime: "03:57 PM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 124,
        title: "class_123",
        startTime: "04:12 PM",
        endTime: "05:07 PM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 125,
        title: "class_124",
        startTime: "05:20 PM",
        endTime: "05:55 PM",
        duration: "35 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 126,
        title: "class_125",
        startTime: "06:05 PM",
        endTime: "06:50 PM",
        duration: "45 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 127,
        title: "class_126",
        startTime: "07:05 PM",
        endTime: "08:00 PM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 128,
        title: "class_127",
        startTime: "08:15 PM",
        endTime: "09:00 PM",
        duration: "45 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 129,
        title: "class_128",
        startTime: "09:02 PM",
        endTime: "09:37 PM",
        duration: "35 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 130,
        title: "class_129",
        startTime: "09:42 PM",
        endTime: "10:37 PM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 131,
        title: "class_130",
        startTime: "10:50 PM",
        endTime: "11:30 PM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
    ],
    Saturday: [
      {
        id: 132,
        title: "class_131",
        startTime: "12:00 AM",
        endTime: "01:00 AM",
        duration: "60 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 133,
        title: "class_132",
        startTime: "01:05 AM",
        endTime: "01:55 AM",
        duration: "50 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 134,
        title: "class_133",
        startTime: "01:57 AM",
        endTime: "02:57 AM",
        duration: "60 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 135,
        title: "class_134",
        startTime: "03:10 AM",
        endTime: "04:05 AM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 136,
        title: "class_135",
        startTime: "04:12 AM",
        endTime: "04:47 AM",
        duration: "35 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 137,
        title: "class_136",
        startTime: "04:55 AM",
        endTime: "05:50 AM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 138,
        title: "class_137",
        startTime: "06:02 AM",
        endTime: "06:57 AM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 139,
        title: "class_138",
        startTime: "07:02 AM",
        endTime: "07:37 AM",
        duration: "35 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 140,
        title: "class_139",
        startTime: "07:47 AM",
        endTime: "08:42 AM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 141,
        title: "class_140",
        startTime: "08:50 AM",
        endTime: "09:20 AM",
        duration: "30 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 142,
        title: "class_141",
        startTime: "09:27 AM",
        endTime: "10:12 AM",
        duration: "45 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 143,
        title: "class_142",
        startTime: "10:17 AM",
        endTime: "11:02 AM",
        duration: "45 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 144,
        title: "class_143",
        startTime: "11:05 AM",
        endTime: "11:40 AM",
        duration: "35 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 145,
        title: "class_144",
        startTime: "11:50 AM",
        endTime: "12:40 PM",
        duration: "50 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 146,
        title: "class_145",
        startTime: "12:42 PM",
        endTime: "01:27 PM",
        duration: "45 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 147,
        title: "class_146",
        startTime: "01:30 PM",
        endTime: "02:10 PM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 148,
        title: "class_147",
        startTime: "02:15 PM",
        endTime: "03:05 PM",
        duration: "50 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 149,
        title: "class_148",
        startTime: "03:10 PM",
        endTime: "04:10 PM",
        duration: "60 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 150,
        title: "class_149",
        startTime: "04:17 PM",
        endTime: "04:57 PM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 151,
        title: "class_150",
        startTime: "05:05 PM",
        endTime: "05:55 PM",
        duration: "50 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 152,
        title: "class_151",
        startTime: "06:02 PM",
        endTime: "07:02 PM",
        duration: "60 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 153,
        title: "class_152",
        startTime: "07:10 PM",
        endTime: "07:50 PM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 154,
        title: "class_153",
        startTime: "08:05 PM",
        endTime: "08:50 PM",
        duration: "45 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 155,
        title: "class_154",
        startTime: "09:02 PM",
        endTime: "09:57 PM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 156,
        title: "class_155",
        startTime: "10:07 PM",
        endTime: "10:37 PM",
        duration: "30 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 157,
        title: "class_156",
        startTime: "10:50 PM",
        endTime: "11:25 PM",
        duration: "35 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
    ],
    Sunday: [
      {
        id: 158,
        title: "class_157",
        startTime: "12:00 AM",
        endTime: "12:40 AM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 159,
        title: "class_158",
        startTime: "12:47 AM",
        endTime: "01:27 AM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 160,
        title: "class_159",
        startTime: "01:32 AM",
        endTime: "02:12 AM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 161,
        title: "class_160",
        startTime: "02:27 AM",
        endTime: "03:12 AM",
        duration: "45 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 162,
        title: "class_161",
        startTime: "03:20 AM",
        endTime: "04:10 AM",
        duration: "50 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 163,
        title: "class_162",
        startTime: "04:15 AM",
        endTime: "04:45 AM",
        duration: "30 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 164,
        title: "class_163",
        startTime: "04:57 AM",
        endTime: "05:27 AM",
        duration: "30 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 165,
        title: "class_164",
        startTime: "05:35 AM",
        endTime: "06:10 AM",
        duration: "35 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 166,
        title: "class_165",
        startTime: "06:20 AM",
        endTime: "07:20 AM",
        duration: "60 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 167,
        title: "class_166",
        startTime: "07:30 AM",
        endTime: "08:20 AM",
        duration: "50 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 168,
        title: "class_167",
        startTime: "08:32 AM",
        endTime: "09:07 AM",
        duration: "35 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 169,
        title: "class_168",
        startTime: "09:17 AM",
        endTime: "10:12 AM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 171,
        title: "class_170",
        startTime: "11:02 AM",
        endTime: "11:47 AM",
        duration: "45 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 172,
        title: "class_171",
        startTime: "12:02 PM",
        endTime: "01:02 PM",
        duration: "60 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 173,
        title: "class_172",
        startTime: "01:12 PM",
        endTime: "01:47 PM",
        duration: "35 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 174,
        title: "class_173",
        startTime: "01:57 PM",
        endTime: "02:47 PM",
        duration: "50 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 175,
        title: "class_174",
        startTime: "02:52 PM",
        endTime: "03:37 PM",
        duration: "45 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 176,
        title: "class_175",
        startTime: "03:47 PM",
        endTime: "04:22 PM",
        duration: "35 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 177,
        title: "class_176",
        startTime: "04:37 PM",
        endTime: "05:32 PM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 178,
        title: "class_177",
        startTime: "05:35 PM",
        endTime: "06:30 PM",
        duration: "55 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 179,
        title: "class_178",
        startTime: "06:40 PM",
        endTime: "07:20 PM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
      {
        id: 180,
        title: "class_179",
        startTime: "07:25 PM",
        endTime: "08:05 PM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Omprakash Tiwari",
      },
      {
        id: 181,
        title: "class_180",
        startTime: "08:15 PM",
        endTime: "09:05 PM",
        duration: "50 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 182,
        title: "class_181",
        startTime: "09:17 PM",
        endTime: "09:57 PM",
        duration: "40 Mins",
        created: "29 days ago",
        facultyName: "Amit Maurya",
      },
      {
        id: 183,
        title: "class_182",
        startTime: "10:10 PM",
        endTime: "10:40 PM",
        duration: "30 Mins",
        created: "29 days ago",
        facultyName: "Ramjeet singh",
      },
      {
        id: 184,
        title: "class_183",
        startTime: "10:50 PM",
        endTime: "11:20 PM",
        duration: "30 Mins",
        created: "29 days ago",
        facultyName: "Priyanshu Singh",
      },
    ],
  },
};
