const data = {
  id: 4,
  title: "C.S.E 4th Year",
  isActive: true,
  totalStudents: 1,
  totalClasses: 8,
  created: "2021-01-25",
  verifiedFaculties: 2,
  totalFaculties: 3,
  weekdayData: {
    Sunday: [],
    Monday: [
      {
        created: "8 days ago",
        duration: "60 Mins",
        endTime: "10:00AM",
        facultyName: "Amit Maurya",
        id: 13,
        startTime: "09:00AM",
        title: "Distributed System",
      },
      {
        created: "8 days ago",
        duration: "59 Mins",
        endTime: "11:00AM",
        facultyName: "Ramjeet Yadav",
        id: 14,
        startTime: "10:01AM",
        title: "Human Values",
      },
      {
        created: "8 days ago",
        duration: "59 Mins",
        endTime: "12:00PM",
        facultyName: "Amit Maurya",
        id: 15,
        startTime: "11:01AM",
        title: "Human Values",
      },
      {
        created: "8 days ago",
        duration: "75 Mins",
        endTime: "02:15PM",
        facultyName: "Amit Maurya",
        id: 16,
        startTime: "01:00PM",
        title: "Electrical System",
      },
    ],
    Tuesday: [
      {
        created: "8 days ago",
        duration: "60 Mins",
        endTime: "10:00AM",
        facultyName: "Amit Maurya",
        id: 17,
        startTime: "09:00AM",
        title: "Distributed System",
      },

      {
        created: "8 days ago",
        duration: "75 Mins",
        endTime: "02:15PM",
        facultyName: "Amit Maurya",
        id: 20,
        startTime: "01:00PM",
        title: "Electrical System",
      },
    ],
    Wednesday: [
      {
        created: "8 days ago",
        duration: "60 Mins",
        endTime: "10:00AM",
        facultyName: "Amit Maurya",
        id: 21,
        startTime: "09:00AM",
        title: "Distributed System",
      },
      {
        created: "8 days ago",
        duration: "59 Mins",
        endTime: "11:00AM",
        facultyName: "Ramjeet Yadav",
        id: 22,
        startTime: "10:01AM",
        title: "Human Values",
      },
      {
        created: "8 days ago",
        duration: "59 Mins",
        endTime: "12:00PM",
        facultyName: "Amit Maurya",
        id: 23,
        startTime: "11:01AM",
        title: "Human Values",
      },
      {
        created: "8 days ago",
        duration: "75 Mins",
        endTime: "02:15PM",
        facultyName: "Amit Maurya",
        id: 24,
        startTime: "01:00PM",
        title: "Electrical System",
      },
    ],
    Thursday: [
      {
        created: "8 days ago",
        duration: "60 Mins",
        endTime: "10:00AM",
        facultyName: "Amit Maurya",
        id: 25,
        startTime: "09:00AM",
        title: "Distributed System",
      },
      {
        created: "8 days ago",
        duration: "59 Mins",
        endTime: "11:00AM",
        facultyName: "Ramjeet Yadav",
        id: 26,
        startTime: "10:01AM",
        title: "Human Values",
      },
      {
        created: "8 days ago",
        duration: "59 Mins",
        endTime: "12:00PM",
        facultyName: "Amit Maurya",
        id: 27,
        startTime: "11:01AM",
        title: "Human Values",
      },
      {
        created: "8 days ago",
        duration: "75 Mins",
        endTime: "02:15PM",
        facultyName: "Amit Maurya",
        id: 28,
        startTime: "01:00PM",
        title: "Electrical System",
      },
    ],
    Friday: [
      {
        created: "8 days ago",
        duration: "60 Mins",
        endTime: "10:00AM",
        facultyName: "Amit Maurya",
        id: 29,
        startTime: "09:00AM",
        title: "Distributed System",
      },
      {
        created: "8 days ago",
        duration: "59 Mins",
        endTime: "11:00AM",
        facultyName: "Ramjeet Yadav",
        id: 30,
        startTime: "10:01AM",
        title: "Human Values",
      },
      {
        created: "8 days ago",
        duration: "59 Mins",
        endTime: "12:00PM",
        facultyName: "Amit Maurya",
        id: 31,
        startTime: "11:01AM",
        title: "Human Values",
      },
      {
        created: "8 days ago",
        duration: "75 Mins",
        endTime: "02:15PM",
        facultyName: "Amit Maurya",
        id: 32,
        startTime: "01:00PM",
        title: "Electrical System",
      },
    ],
    Saturday: [
      {
        created: "8 days ago",
        duration: "60 Mins",
        endTime: "10:00AM",
        facultyName: "Amit Maurya",
        id: 33,
        startTime: "09:00AM",
        title: "Distributed System",
      },
      {
        created: "8 days ago",
        duration: "59 Mins",
        endTime: "11:00AM",
        facultyName: "Ramjeet Yadav",
        id: 34,
        startTime: "10:01AM",
        title: "Human Values",
      },
      {
        created: "8 days ago",
        duration: "59 Mins",
        endTime: "12:00PM",
        facultyName: "Amit Maurya",
        id: 35,
        startTime: "11:01AM",
        title: "Human Values",
      },
      {
        created: "8 days ago",
        duration: "75 Mins",
        endTime: "02:15PM",
        facultyName: "Amit Maurya",
        id: 36,
        startTime: "01:00PM",
        title: "Electrical System",
      },
    ],
  },
};

export default data;
